version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
    - "1883:1883"
    volumes:
    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ./mosquitto_passwd:/mosquitto/config/mosquitto_passwd

  simulator:
    build: .
    depends_on:
    - mqtt
    environment:
      MQTT_BROKER_URL: mqtt://mqtt:1883
      DATA_FREQUENCY: ${DATA_FREQUENCY:-5000}
      SENSOR_COUNT: ${SENSOR_COUNT:-4}
      MQTT_QOS: ${MQTT_QOS:-0}
    env_file:
    - .env

  track-api:
    build: ./track/
    depends_on:
    - simulator
    environment:
      MQTT_BROKER_URL: mqtt://mqtt:1883
      API_URL: https://api.g2.south-squad.io/registers/
      RASP_NAME: TestRaspberry
